# POST https://login-api-demo-dlw6.onrender.com/register
# Content-Type: application/json

# {
#   "username": "qwe",
#   "password": "789"
# }

POST https://login-api-demo-dlw6.onrender.com/login
Content-Type: application/json

{
  "username": "qwe",
  "password": "789"
}
